# Generated by Django 4.2.25 on 2025-10-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('abc', models.TextField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
